apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lilritch/task-manager-devops.git
    targetRevision: main
    path: helm/task-manager
    helm:
      values: |
        ingress:
          host: task-manager-gitops.local
  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
