apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  SECRET_KEY: change-me-before-real-deploy
  GITHUB_TOKEN: ""
  GITHUB_OWNER: Lilritch
  GITHUB_REPO: task-manager-devops
  SLACK_SIGNING_SECRET: ""
  SLACK_DEFAULT_USER_EMAIL: ""
  SLACK_ALLOW_UNSIGNED: "false"
